### ISSUE TITLE
Warning: prerequisite perl 5.006 not found.

### ISSUE THREAD

**Issue by hvds** [tokuhirom/Test-Requires#15]
Test-Requires-0.10 Makefile.PL has "perl => 5.006" in the PREREQ_PM section, but I have no perl.pm module.

I think this should be MIN_PERL_VERSION instead.

Hugo

**Comment by tokuhirom** [comment]
hm? i don't know about MIN_PERL_VERSION.
And   "perl => 5.006" works well on my environment.

--
tokuhirom
